{% set name = "tinuous" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 77a104e5649a8a4ab7911412e7b5fb1c8bf3ea1df8e4ec3779b77501685da931

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tinuous = tinuous.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - click
    - click-loglevel >=0.2
    - datalad
    - in_place >=0.4
    - pydantic 1.*
    - PyGithub
    - python-dateutil >=2.7
    - python-dotenv
    - PyYAML
    - requests 2.*

test:
  imports:
    - tinuous
  commands:
    - tinuous --help

about:
  home: https://github.com/con/tinuous
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download build logs from GitHub Actions, Travis, and Appveyor
  description: |
    tinuous is a command for downloading build logs for a GitHub repository
    from GitHub Actions, Travis-CI.com, and/or Appveyor.
  dev_url: https://github.com/con/tinuous

extra:
  recipe-maintainers:
    - jwodder
    - yarikoptic
