{% set name = "tinuous" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0a45e1d559feccc8a8b6fd46be82afb1bf30f0942f6c30cff5504a90106d92e2

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tinuous = tinuous.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioningit
  run:
    - python >={{ python_min }}
    - click
    - click-loglevel >=0.2
    - datalad
    - ghtoken >=0.1,<1.0
    - in_place 1.*
    - pydantic 2.*
    - python-dateutil >=2.7
    - python-dotenv
    - PyYAML
    - requests 2.*
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - tinuous
  commands:
    - tinuous --help

about:
  home: https://github.com/con/tinuous
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download build logs from GitHub Actions, Travis, and Appveyor
  description: |
    tinuous is a command for downloading build logs for a GitHub repository
    from GitHub Actions, Travis-CI.com, and/or Appveyor.
  dev_url: https://github.com/con/tinuous

extra:
  recipe-maintainers:
    - jwodder
    - yarikoptic
